#!/bin/sh
# Webux universal installer
# Usage: curl -fsSL https://example.com/install.sh | sudo sh
# Or:    sudo sh install.sh [--version v1.2.3] [--no-service]
#
# Override the source repository — needed when the release assets live under a
# fork rather than upstream:
#   WEBUX_REPO=sincerely-hello-world/webux sudo -E sh install.sh
set -e

# 默认指向上游仓库。本仓库是 fork, 而 fork 发布的资产在
# sincerely-hello-world/webux 下, 所以从 fork 发版后请显式覆盖 REPO。
# 注意: 用 `sudo -E` 或 `sudo WEBUX_REPO=...` 传入, 否则 sudo 会丢掉该变量。
REPO="${WEBUX_REPO:-brendan4linux/webux}"
INSTALL_DIR="/usr/local/bin"
DATA_DIR="/var/lib/webux"
CONFIG_DIR="/etc/webux"
SERVICE_NAME="webux"
NO_SERVICE=0
VERSION=""

# ── Parse args ────────────────────────────────────────────
while [ $# -gt 0 ]; do
  case "$1" in
    --version) VERSION="$2"; shift 2 ;;
    --no-service) NO_SERVICE=1; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Colours ───────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'

info()    { printf "${BLUE}→${NC} %s\n" "$*"; }
success() { printf "${GREEN}✓${NC} %s\n" "$*"; }
warn()    { printf "${YELLOW}!${NC} %s\n" "$*"; }
die()     { printf "${RED}✗${NC} %s\n" "$*" >&2; exit 1; }

# ── Root check ────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
  die "This installer must be run as root (sudo sh install.sh)"
fi

printf "\n${BOLD}  Webux Linux Management Panel — Installer${NC}\n\n"

# ── Detect architecture ───────────────────────────────────
# Must stay in sync with .goreleaser.yaml -> builds.targets.
# The value echoed here is the GoReleaser {{ .Arch }} suffix, which is what the
# release asset name actually contains — NOT the distro package arch name.
# For 32-bit x86 those differ, and not even consistently: the tar.gz archives say
# `386`, while the .deb and .rpm are both `i386` and the pacman package is `i686`.
# armv6 is deliberately absent: there is no linux_arm_6 target, so listing it
# would only ever produce a 404 further down.
detect_arch() {
  arch=$(uname -m)
  case "$arch" in
    x86_64|amd64)     echo "amd64" ;;
    # 32-bit x86. uname reports i386/i486/i586/i686 depending on kernel and
    # userspace; GoReleaser's GOARCH name for all of them is `386`.
    i386|i486|i586|i686) echo "386" ;;
    aarch64|arm64)    echo "arm64" ;;
    armv7l|armv7)     echo "armv7" ;;
    *)                die "Unsupported architecture: $arch" ;;
  esac
}

ARCH=$(detect_arch)
info "Architecture: $ARCH"

# ── Detect OS ─────────────────────────────────────────────
detect_os() {
  if [ -f /etc/os-release ]; then
    . /etc/os-release
    echo "$ID"
  elif [ -f /etc/redhat-release ]; then
    echo "rhel"
  elif [ -f /etc/debian_version ]; then
    echo "debian"
  else
    echo "unknown"
  fi
}

OS=$(detect_os)
info "OS: $OS"

# ── Detect init system ────────────────────────────────────
detect_init() {
  if [ -d /run/systemd/system ]; then
    echo "systemd"
  elif [ -f /sbin/openrc ]; then
    echo "openrc"
  elif [ -f /etc/init.d/cron ] || [ -f /etc/init.d/crond ]; then
    echo "sysv"
  else
    echo "unknown"
  fi
}

INIT=$(detect_init)
info "Init system: $INIT"

# ── Detect download tool ──────────────────────────────────
if command -v curl >/dev/null 2>&1; then
  DOWNLOAD="curl -fsSL"
elif command -v wget >/dev/null 2>&1; then
  DOWNLOAD="wget -qO-"
else
  die "Neither curl nor wget found — install one and retry"
fi

# ── Resolve version ───────────────────────────────────────
if [ -z "$VERSION" ]; then
  info "Fetching latest version..."
  VERSION=$($DOWNLOAD "https://api.github.com/repos/$REPO/releases/latest" \
    | grep '"tag_name"' | sed 's/.*"tag_name": *"\(.*\)".*/\1/')
  [ -z "$VERSION" ] && die "Could not determine latest version"
fi
info "Version: $VERSION"

# ── Download release archive ──────────────────────────────
# The primary release asset is the "installer tree": a root-relative tar.gz
# that also carries etc/webux/config.yaml, which keeps the config template
# below in step with what the .deb/.rpm/.pkg.tar.zst packages install.
# (A binary-only archive exists as well, named ..._bin.tar.gz.)
#
# The asset name is generated by .goreleaser.yaml and uses GoReleaser's
# {{ .Version }}, which carries no leading "v" — while the git tag (and thus
# $VERSION, whether it came from --version or the GitHub API tag_name) does.
# Without stripping it here the URL is a guaranteed 404.
ASSET_VERSION="${VERSION#v}"
ASSET_NAME="webux_${ASSET_VERSION}_linux_${ARCH}"
DOWNLOAD_URL="https://github.com/$REPO/releases/download/$VERSION/${ASSET_NAME}.tar.gz"
TMPDIR=$(mktemp -d)
trap 'rm -rf $TMPDIR' EXIT

info "Downloading ${ASSET_NAME}.tar.gz..."
$DOWNLOAD "$DOWNLOAD_URL" > "$TMPDIR/webux.tar.gz" || \
  die "Download failed: $DOWNLOAD_URL"

tar -xzf "$TMPDIR/webux.tar.gz" -C "$TMPDIR"

# Find the binary in the extracted contents
BINARY=$(find "$TMPDIR" -name "webux" -type f | head -1)
[ -z "$BINARY" ] && die "Could not find webux binary in archive"

# ── Install binary ────────────────────────────────────────
# mkdir first: /usr/local/bin usually exists (FHS), but minimal and container
# images — Alpine, OpenWrt, slim base images — routinely ship without it, and
# a bare `install` there fails with a confusing "No such file or directory"
# even though everything else about the install was fine.
mkdir -p "$INSTALL_DIR"
info "Installing to $INSTALL_DIR/webux..."
install -m 755 "$BINARY" "$INSTALL_DIR/webux"
success "Binary installed"

# ── Create directories ────────────────────────────────────
mkdir -p "$DATA_DIR" "$CONFIG_DIR"
chmod 750 "$DATA_DIR" "$CONFIG_DIR"

# ── Install config (don't overwrite existing) ─────────────
if [ ! -f "$CONFIG_DIR/config.yaml" ]; then
  # Prefer the template shipped inside the release tarball — that is the very
  # file packaging installs, so scripts/config.yaml stays the single source of
  # truth and the two cannot drift apart.
  TEMPLATE="$TMPDIR/etc/webux/config.yaml"
  if [ -f "$TEMPLATE" ]; then
    install -m 644 "$TEMPLATE" "$CONFIG_DIR/config.yaml"
  else
    # Unexpected archive layout — still write a valid, complete config.
    cat > "$CONFIG_DIR/config.yaml" << CONFEOF
# Webux configuration — full reference at https://github.com/$REPO
listen_addr: ":8989"
data_dir: "$DATA_DIR"
tls_cert_file: ""
tls_key_file: ""
log_level: "info"
learn_mode: true

auth:
  bypass_token: ""
  jwt_secret: ""
  disabled: false
  allowed_users: []

files:
  root: "/home"
CONFEOF
  fi
  success "Config written to $CONFIG_DIR/config.yaml"
else
  warn "Config already exists at $CONFIG_DIR/config.yaml — skipping"
fi

# ── Install service ───────────────────────────────────────
if [ "$NO_SERVICE" -eq 0 ]; then
  case "$INIT" in
    systemd)
      info "Installing systemd service..."
      cat > /etc/systemd/system/webux.service << SVCEOF
[Unit]
Description=Webux Linux Management Panel
Documentation=https://github.com/$REPO
# network-online.target, not network.target: the latter is ordered very early
# and does not guarantee a usable address for the admin to connect to.
Wants=network-online.target
After=network-online.target
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
Type=simple
# webux administers this host and therefore runs as root by design. The usual
# ProtectSystem=/ProtectHome=/NoNewPrivileges= sandbox is deliberately not
# applied — it would break shell access, file browsing and package management.
User=root
Group=root
# --config is the only way to point the binary at its config file; the
# WEBUX_CONFIG environment variable is not read.
ExecStart=$INSTALL_DIR/webux --config $CONFIG_DIR/config.yaml
Restart=on-failure
RestartSec=5s
# WEBUX_DATA_DIR IS honoured by the binary — keep it in step with data_dir.
# StateDirectoryMode is set explicitly because systemd's default is 0755,
# which would undo the 0750 applied above.
Environment=WEBUX_DATA_DIR=$DATA_DIR
StateDirectory=webux
StateDirectoryMode=0750
# journald only — also writing to a file would bypass log rotation.
StandardOutput=journal
StandardError=journal
SyslogIdentifier=webux

[Install]
WantedBy=multi-user.target
SVCEOF
      systemctl daemon-reload
      systemctl enable webux
      systemctl start webux
      success "systemd service installed and started"
      ;;

    openrc)
      info "Installing OpenRC service..."
      cat > /etc/init.d/webux << RCEOF
#!/sbin/openrc-run
name="webux"
description="Webux Linux Management Panel"
command="$INSTALL_DIR/webux"
# --config is the only way to point the binary at its config file; the
# WEBUX_CONFIG environment variable is not read.
command_args="--config $CONFIG_DIR/config.yaml"
command_background=true
pidfile="/run/webux.pid"
# WEBUX_DATA_DIR IS honoured by the binary.
export WEBUX_DATA_DIR="$DATA_DIR"
RCEOF
      chmod +x /etc/init.d/webux
      rc-update add webux default
      rc-service webux start
      success "OpenRC service installed and started"
      ;;

    sysv)
      info "Installing SysV init script..."
      cat > /etc/init.d/webux << SVEOF
#!/bin/sh
### BEGIN INIT INFO
# Provides:          webux
# Required-Start:    \$network
# Required-Stop:     \$network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Webux Linux Management Panel
### END INIT INFO
NAME=webux
DAEMON=$INSTALL_DIR/webux
CONFIG=$CONFIG_DIR/config.yaml
PIDFILE=/run/webux.pid
DAEMON_OPTS="--config \$CONFIG"
# WEBUX_DATA_DIR IS honoured by the binary; WEBUX_CONFIG is not.
export WEBUX_DATA_DIR="$DATA_DIR"
case "\$1" in
  start)
    start-stop-daemon --start --background --make-pidfile \
      --pidfile \$PIDFILE --exec \$DAEMON -- \$DAEMON_OPTS
    ;;
  stop)
    start-stop-daemon --stop --pidfile \$PIDFILE
    rm -f \$PIDFILE
    ;;
  restart) \$0 stop; sleep 1; \$0 start ;;
  status)
    [ -f \$PIDFILE ] && kill -0 \$(cat \$PIDFILE) 2>/dev/null && echo "running" && exit 0
    echo "stopped"; exit 1 ;;
  *) echo "Usage: \$0 {start|stop|restart|status}"; exit 1 ;;
esac
SVEOF
      chmod +x /etc/init.d/webux
      if command -v update-rc.d >/dev/null 2>&1; then
        update-rc.d webux defaults
      elif command -v chkconfig >/dev/null 2>&1; then
        chkconfig --add webux
        chkconfig webux on
      fi
      /etc/init.d/webux start
      success "SysV init script installed and started"
      ;;

    *)
      warn "Unknown init system — binary installed but no service configured"
      warn "Start manually: WEBUX_DATA_DIR=$DATA_DIR $INSTALL_DIR/webux"
      ;;
  esac
fi

# ── Done ──────────────────────────────────────────────────
# Report where the panel is actually reachable. There is no bare `port:` key in
# the schema — listen_addr is "host:port" or ":port" — so take the text after
# the last colon. (This block used to hardcode port 9090 over plain http while
# the shipped config listens on :8989 and serves TLS, so every install printed
# a URL that could never work.)
PORT=8989
if [ -f "$CONFIG_DIR/config.yaml" ]; then
  ADDR=$(sed -n 's/^[[:space:]]*listen_addr:[[:space:]]*//p' "$CONFIG_DIR/config.yaml" \
         | head -1 | tr -d '"\'\'' ')
  [ -n "$ADDR" ] && PORT="${ADDR##*:}"
fi
HOST_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
[ -z "$HOST_IP" ] && HOST_IP="localhost"

printf "\n${GREEN}${BOLD}  Webux $VERSION installed successfully!${NC}\n"
printf "  Panel:  ${BOLD}https://${HOST_IP}:${PORT}${NC}\n"
printf "  Config: $CONFIG_DIR/config.yaml\n"
printf "  Data:   $DATA_DIR\n\n"
printf "  Note: self-signed cert — accept the browser security warning on first visit\n\n"
